### ISSUE TITLE
Sound extremely distorted

### ISSUE THREAD

**Issue by patrickjboettcher** [rorywalsh/CsoundUnity#15]
Hi everyone,

whenever I attach a Csound Unity (Script) and an Audio Source component on an object in Unity I get an extremely distorted and loud sound when I start Play Mode. Added to that I get the following message in the console: 
`could not open library 'C:/Users/[...]/[...]/Assets/StreamingAssets\CsoundUnityNative.dll' (-1)`

The Csound file itself plays fine in CsoundQt.

Any ideas how to fix this?
I tried different audio settings and different unity versions, but nothing here solves my problem.

**Comment by giovannibedetti** [comment]
where did you get CsoundUnity?
what OS are you on?

**Comment by patrickjboettcher** [comment]
> 
> 
> where did you get CsoundUnity?
> what OS are you on?

I'm on Windows 10 and I downloaded the .zip of Csound Unity from rorywalsh.github.io/CsoundUnity.

**Comment by giovannibedetti** [comment]
What version of Unity are you on?
Could you try the development version of CsoundUnity to see if this is solved?
First create a clean project.
From the Unity Package Manager, add a new package from Git with this url:
https://github.com/rorywalsh/CsoundUnity.git#develop
wait some time for the scripts to be imported, then try your csd again

**Comment by patrickjboettcher** [comment]
I tried Unity Versions 2017.3.0f3 and 2019.3.0f6.
I did everything you wrote. Now my csd doesn't play at all because
`CsoundUnity is overriding the orchestra ksmps value to best match Unity's audio settings, i.e, 32 ksmps`
How do I adjust Unity's audio settings? System Sample Rate is already set to 44100 to match my .csd-file.

**Comment by giovannibedetti** [comment]
This is normal, we are overriding sr and ksmps to be compliant with Unity sample rate. We found that Csound in Unity works only if ksmps is 32. So there's no need to modify the project audio settings (btw you can find them under Edit/Project Settings/Audio, if system sample rate is 0 the system sample rate is used) nor the sr in the Csound file.
Could you please post here a pastebin link with the csd you are using so that I can take a look?

**Comment by patrickjboettcher** [comment]
Thanks! With that information I was able to solve the problem myself. I worked with a csd that had a ksmps value of 10, so I changed that to 32. Then I changed 0dbfs to 1 and I adjusted the volume of the csd. Now it works fine in Unity.
