### ISSUE TITLE
SendScoreEvent doesn't work

### ISSUE THREAD

**Issue by simogreg** [rorywalsh/CsoundUnity#16]
hi i'm trying to use the sendscoreevent function, but it doesn't work, i try to send an event in score every time i there is a collision, but csound log tell me that Score finished in csoundPerformKsmps() and i don't listen anything. 
I've also noticed that when I instantiate an object with a sound attached to it, after a few seconds a distorted high pitched sound occurs, what can i do?
Thank you

**Comment by giovannibedetti** [comment]
If the score finished then csound is not accepting score events anymore. 
Ensure you have something like this in the csd score section:

```
<CsScore>
;causes Csound to run for about 7000 years...
f0 z
</CsScore>

```
Where did you get CsoundUnity? What OS are you on? Which Unity version?

**Comment by simogreg** [comment]
Ok thank you! This work fine, i have the latest version of CsoundUnity, i download it from the github download pages, the version of Unity is the latest.

**Comment by giovannibedetti** [comment]
ok I'm closing this.
Could you please create another issue about the object with sound attached?
Please explain in detail what you're doing!
