### ISSUE TITLE
Csound cannot open a .wav file in the same directory of the script

### ISSUE THREAD

**Issue by simogreg** [rorywalsh/CsoundUnity#17]
Hi, i'm trying to use the opcode ftgen to open a wav file in the directory CsoundFiles locate in the scripts folder, if i try to run the script without Unity it works fine, but when i run it on unity Csound log tells me that he can't open the wave file.
Thank you

**Comment by giovannibedetti** [comment]
Did you read this section of the docs? https://rorywalsh.github.io/CsoundUnity/docs.html#reading_files_with_csound

Basically the audio file should be inside the StreamingAssets folder, and you must provide the full path:
[look here for an example](https://forum.cabbageaudio.com/t/csoundunity-beginner-questions/1903/37?u=giovannibedetti)
Btw I suggest you to try the develop version of CsoundUnity: remove all the references to the 2.3 version, open PackageManager window, add package via git, and paste this url: https://github.com/rorywalsh/CsoundUnity.git#develop
Close the window and wait some time for the scripts to be imported.

**Comment by simogreg** [comment]
Thank you,  I read that section a long time ago and I forgot it, now  everything's clear!

**Comment by giovannibedetti** [comment]
@all-contributors add @simogreg for bug
