### ISSUE TITLE
NullReferenceException when sending data from Unity to Csound

### ISSUE THREAD

**Issue by patrickjboettcher** [rorywalsh/CsoundUnity#19]
I want to control aspects of my .csd file through Csounds channel system in realtime.

However, Unity keeps telling me that there is a NullReferenceException either in the CsoundUnity.cs file or in my PlayerController.cs script.

Unity refers to the following lines of code in the CsoundUnity.cs file (from line 690):

```
 public void SetChannel(string channel, MYFLT val)
    {
        csound.SetChannel(channel, val);
    }
```

If Unity doesn't refer to that, it refers to the my following code in my Awake() function of my PlayerController.cs script:

```
 private void Awake()
    {
       [...] // player controller script

        csound = GetComponent<CsoundUnity>();
        csound.SetChannel("notelength", notelength);
    }

```
This results in not being able to move my player.
If I remove my attempts of sending data to Csound I can move my player and everything is fine.
My .csd file and my PlayerController.cs script are attached to my player.

Any idea how to fix this?

**Comment by giovannibedetti** [comment]
Try calling GetComponent in Start instead of Awake, and if it's not enough you can wait until Csound is initialized:

```
IEnumerator Start() {
        csound = GetComponent<CsoundUnity>();

        while (!csound.IsInitialized) {
            yield return null;
        }
        //do something with Csound
    }
```

Or you can set a callback to know when it is initialized:


```
private void Start()
{
    csound = GetComponent<CsoundUnity>();
    csound.OnCsoundInitialized += OnCsoundInitialized;
}

private void OnCsoundInitialized()
{
    //do something with Csound
}
```

**Comment by patrickjboettcher** [comment]
The second approach works and I can move my player model, but then Unity refers to my update function in the same script exactly behind _notelength++;_ with a NullReferenceException:

```
void Update()
{

        if (Input.GetKeyDown("l"))
        {
            notelength++;
            csound.SetChannel("notelength", notelength);
        }
}
```

Any idea on what I should do here?

**Comment by giovannibedetti** [comment]
Another way to be sure that CsoundUnity is found is to create a public or serialized field like this:

`public CsoundUnity csound;
`
or

```
[SerializeField]
private CsoundUnity csound;
```

and drag the CsoundUnity GameObject in the created field in your script inspector.
Another potential problem is that the control channel you're targeting doesn't exist. But that wouldn't cause a NullReferenceException but an error from Csound. Try enabling the Log Csound Output toggle and have a look at the logs. 
If you can please post the portion of code where you define the control channel in your csd.

**Comment by patrickjboettcher** [comment]
Here's how I access the channel in my .csd file:
`gidur  chnget "notelength"`
Therefore it is declared as a global variable. Is that okay? Or does it need to be inside an instrument?

I believe that my problem is that my PlayerController script can't find the CsoundUnity GameObject. It says _None (Csound Unity)_. I can't drag anything into that field created by my code
`[SerializeField] private CsoundUnity csound;`
When I open the box in that field to select the object nothing shows up.
I have two folders, one of them is the _Assets_ folder and the other one is the _Packages_ folder, which contains the CsoundUnity package. I don't know where to find that CsoundUnity GameObject you're talking about. Is it the csound64.dll? Or CsoundUnity.cs? Do these objects need to be inside my _Assets_ folder to access them?

**Comment by giovannibedetti** [comment]
Just add CsoundUnity as a component in any GameObject you have in the scene (so it must be present in Hierarchy)
![Schermata 2020-07-14 alle 13 12 04](https://user-images.githubusercontent.com/1912983/87424486-ed67de00-c5d3-11ea-9ad7-acb257c88d6b.png)
![Schermata 2020-07-14 alle 13 12 23](https://user-images.githubusercontent.com/1912983/87424496-f0fb6500-c5d3-11ea-8fa1-d7d2c17f4a27.png)
![Schermata 2020-07-14 alle 13 12 50](https://user-images.githubusercontent.com/1912983/87424500-f3f65580-c5d3-11ea-907a-271f8a23c7a2.png)
then select your csd asset (must be in any folder under "Assets")
Notice the AudioSource component is added too, so the audio position in 3D is dependent on the transform position of this GameObject.

`gidur chnget "notelength"`

This is ok but it is evaluated just once.
Try putting it in an instrument that is always active.
You can have an instrument play forever with:
`i1 0 z`

**Comment by patrickjboettcher** [comment]
Thank you so far!
Now Unity tells me "Assertion failed UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)" and refers to the following line of code in my PlayerController.cs script:
`public int notelength = 9;`
The Log Csound Output tells me 
```
error: syntax error, unexpected STRING_TOKEN  (token """)
from file *string* (1)
line 65:
>>>UnityEngine.MonoBehaviour:print(Object)<<<
Unexpected untyped word alwayson when expecting a variable
Parsing failed due to invalid input!
```
In my .csd file I'm using the alwayson opcode for my player instrument, which triggers different instruments, and my reverb instrument (which adds reverb).
This is how the most relevant part of my .csd file looks:
```
gidur  chnget "notelength"						   ; DURATION OF LONG NOTES (this must be line 65 he refers to)
gidur2 init gidur/2								    ; DURATION OF SHORT NOTE

;------------------------------- REVERB & PLAYER SETTINGS

gasendL, gasendR init 0								; INITIALIZE REVERB BUS

alwayson "player"									; PLAYER WILL BE RUN UNTIL USER ENDS THE SCRIPT
alwayson "reverb"									; REVERB WILL BE RUN UNTIL USER ENDS THE SCRIPT

;-------------------------------

		instr player
		ktrig  metro 0.15								; TRIGGER 1 FOR SINE_OSC & SAW
		ktrig2 metro 0.15								; TRIGGER 2 FOR GONG
		ktrig3 metro 0.30								; TRIGGER 3 FOR SINE
		
		schedkwhen ktrig, 0, 0, "sine_osc", 0, gidur 		; TRIGGER SINE_OSC
		schedkwhen ktrig, 18, 36, "saw", 96, gidur 			; TRIGGER SAW
		schedkwhen ktrig2, 0, 0, "pluck", 18, gidur2	    ; TRIGGER PLUCK AFTER 18 SECONDS
		schedkwhen ktrig3, 0, 0, "sine", 36, gidur2	        ; TRIGGER SINE AFTER 36 SECONDS 
		endin
```
With replacing _chnget "notelength"_ with _init 9_ my .csd file runs fine.

**Comment by giovannibedetti** [comment]
Try this:
```
gidur init 0
gidur2 init 0

alwayson "ui"

instr ui
gidur chnget "notelength"
gidur2 = gidur/2
endin
```
but I suspect the _alwayson_ opcode is not found. Which OS are you on?

**Comment by rorywalsh** [comment]
Hi guys. I'm late to the party! Looks like `alwayson` is not found. Can you just replace those lines with:

```
schedule("player", 0, -1)
schedule("reverb", 0, -1)
```

It gives you the same functionality using Csound internal opcodes.

**Comment by patrickjboettcher** [comment]
Thank you for helping!
Everything now works fine.
