### ISSUE TITLE
Audio Only on Left Channel

### ISSUE THREAD

**Issue by tadashibashi** [rorywalsh/CsoundUnity#2]
In both Unity 5.3.4 on Windows and Unity 5.3.5 on Mac I'm having issues with having audio only playing on one channel, the left side only. I downloaded and imported the 2.0 packages for each operating system respectively. 

I'm not sure if it is printing both channels to mono and playing only on the left side or if it is stereo minus the right channel. I tried changing the Unity Audio Source's spatial blend to 3D to no avail.

 Testing the csound file in Cabbage it works completely fine with audio on both channels.

**Comment by cabbageaudio** [comment]
Sorry for not spotting this sooner. Unfortunately I'm away on holidays at
the moment and won't be too look into this until I get back next week. Do
you have number of channels to 2? I guess you do. Hmmm. I have an updated
version of this package back at home but I won't be able to update the git
repository until I get back. In the meantime perhaps you could try the
Csound fmod plugin?

http://csound.github.io/site/news/2016/07/15/fmod_and_csound

**Comment by ghost** [comment]
I caught a bug in the CsoundUnity::processBlock(float[] samples, int numChannel) method which causes the problem. Sample is never written into the right channel as i is incremented by numChannels and sample is always assigned to sample[i]. 
To get sound from the right channel, sample should be assigned to sample[i+1] and i should be limited to less than samples-Length-numChannels.

`public void processBlock(float[] samples, int numChannels){`
    `if (compiledOk){`
           `// i should be less than or equal to samples.Length-numChannels to prevent index out of range.`
            `
for (int i = 0; i <= samples.Length-numChannels; i = i + numChannels, ksmpsIndex = ksmpsIndex + numChannels){
`
               `if (mute == true)`
                    `samples[i] = 0f;`
                `else {`
                   `//pass audio from AudioSource clip to Csound`
                   `if (processClipAudio)`
                 `{`
                      `setSample(i, 0, samples[i]);`
                     `if (numChannels == 2)`
                          `setSample(i, 1, samples[i + 1]);`
                   `}`
                  `//Csound's buffer sizes can be different to that of Unity, therefore we need`
                 `//to call performKsmps() only when ksmps samples have been processed`
                  `if ((ksmpsIndex >= ksmps) && (ksmps > 0))`
                 `{`
                        `performKsmps();`
                        `ksmpsIndex = 0;`
                 `}`
                   `//write output from Csound to AudioSource`
                   `samples[i] = (float)(getSample(ksmpsIndex, 0) / zerdbfs);`  
                   `//sample should be writing to samples[i+1] instead of samples[i]`
                    `if (numChannels == 2)`
                     `samples[i+1] = (float)(getSample(ksmpsIndex + 1, 1) / zerdbfs);`
               `}`
           `}`
       `}`
   `}`

**Comment by rorywalsh** [comment]
Ah yes, good spot. I had already addressed the issue of the audio only going to the left channel, but you're right about about the for loop. I'm surprised I didn't hit an issue here when I was working with it myself. I think C# is a lot more forgiving then C! I have to do some audio for a game this week so I'll update the source then.

**Comment by rorywalsh** [comment]
Actually, I think my for loop was fine. I looked at it again, and because I'm doing a straight 'while less than' it works fine. In your case you're doing a 'less than or equal to'. Anyhow, the main issue of audio only going to one channel is now solved, so I'm going to close out this issue. Cheers.

**Comment by danielrothmann** [comment]
Hi Rory,

Thanks for making this! I encountered the same issue as well - only sound in the left speaker, both on new projects and the demo scenes. 

I found that a good solution was to add a channel loop in the processBlock(). This way it also supports any additional number of channels without special cases:

```
for (int i = 0; i < samples.Length; i += numChannels, ksmpsIndex += numChannels)
            {
                for (int channel = 0; channel < numChannels; channel++)
                {
                    if (mute == true)
                        samples[i + channel] = 0.0f;
                    else
                    {
                        if (processClipAudio)
                            setSample(i + channel, channel, samples[i + channel]);

                        if ((ksmpsIndex >= ksmps) && (ksmps > 0))
                        {
                            performKsmps();
                            ksmpsIndex = 0;
                        }

                        samples[i + channel] = (float)(getSample(ksmpsIndex, channel) / zerdbfs);
                    }
                }
            }
```

**Comment by rorywalsh** [comment]
Thanks Daniel. I've replaced my code with your updated method and credited you in the git commit. I'm assuming it all runs fine, I won't have a chance to test it for a while ;)
