### ISSUE TITLE
CsoundUnity.cs has unresolved git merge issue

### ISSUE THREAD

**Issue by kunstmusik** [rorywalsh/CsoundUnity#20]
https://github.com/rorywalsh/CsoundUnity/blob/master/CsoundUnityScripts/CsoundUnity.cs#L80-L86

I'm not sure what is supposed to be here but I saw this looking through the source code for the project.

**Comment by giovannibedetti** [comment]
The master branch hasn't been updated recently. This merge issue was introduced in the last commit, when we started working on the new 'develop' branch. The newest code is there.

**Comment by rorywalsh** [comment]
Sorry guys, only seeing this now. @kunstmusik stay away from the master branch for now. The dev branch is where it's at ;)

**Comment by giovannibedetti** [comment]
closing since the develop branch has no merge issues
