### ISSUE TITLE
SemVer release versions

### ISSUE THREAD

**Issue by runette** [rorywalsh/CsoundUnity#29]
Hi.

Thanks for this package

I would like to be able to access the package through  [openUPM](https://www.openupm.com). This takes the release from the GitHub repo and makes them available through a scoped registry - thus making dependency management and version control easier.

There is only one requirement - the tag included in the package has to be semver compliant and they are not at the moment - i.e v3.0.0 or v3.0.1 as opposed to v3.0.

Would it be possible to create a v3.0.1 release in GH and to use semver tags going forward?

**Comment by giovannibedetti** [comment]
You're right I have been a bit lazy ;)
I published a new release, version 3.1.0. 
I have no experience with upm so probably that is not enough. If you can offer support with this I am more than happy to give you full access to the repo.
From now on I promise I will follow semver requirements!

**Comment by giovannibedetti** [comment]
Got the openUPM badge! 
Feel free to reopen this if there's some issue.

**Comment by runette** [comment]
Thanks. As I guess you have seen now - there is nothing else to do, openUPM will publish and valid Unity Package release that you create as a release as long as the tag names are semver compliant.

**Comment by giovannibedetti** [comment]
@all-contributors add @runette for tool
