### ISSUE TITLE
trouble starting CsoundUnity demos

### ISSUE THREAD

**Issue by metaphysician** [rorywalsh/CsoundUnity#3]
this is more than likely a user error on my part, but i cannot get sound out of the CsoundUnity project demos on my mac running Unity 5.5.1. first error that comes up:

DllNotFoundException: /Assets/StreamingAssets/CsoundLib64.framework/CsoundLib64
CsoundUnityBridge..ctor (System.String csoundDir, System.String csdFile) (at Assets/Scripts/CsoundUnityScripts/CsoundUnityBridge.cs:49)
CsoundUnity.Awake () (at Assets/Scripts/CsoundUnityScripts/CsoundUnity.cs:105)

path appears to be correct. DLL is residing at Assets/StreamingAssets/CSoundLib64.framework

any clues? seem like a path issue, really. would love to try out CSound in Unity. thanks!

**Comment by cabbageaudio** [comment]
Install Csound first.
http://csound.github.io/download.html
Then try it. If that works we can then figure out why it doesn't work with
the included one.

**Comment by metaphysician** [comment]
beautiful! did the trick. only one last question. if i make a build, hopefully the build will use the included frameworks instead? meanwhile i'll go and check out your docs and videos on Unity Csound. and i'll post any further questions to cabbageaudio. thanks!

**Comment by cabbageaudio** [comment]
Great. I'll look into the standalone build. Another user was asking about
that too. It's works OK on windows AFAIK. I'll try the same approach on OSX
and let you know.
