### ISSUE TITLE
LinkButton reference with latest package

### ISSUE THREAD

**Issue by nathanjams** [rorywalsh/CsoundUnity#34]
Hello, 

Just tried installing the latest (3.3.0) in Unity 2020.3.32 on Windows 10 and I get this error: Library\PackageCache\com.csound.csoundunity@058320a7cf\Editor\CsoundUnityEditor.cs(403,27): error CS0117: 'EditorGUI' does not contain a definition for 'LinkButton'

Thank you for this package, I can not wait to get started with it.
Nathan

**Comment by giovannibedetti** [comment]
Yes, sorry for that, I haven't tested the latest release on older Unity versions.
I will add a check for older versions and will draft a new release asap.
The LinkButton has been added in Unity 2021, so while waiting for the new release you will need to use a Unity version above that to be able to use the package.
Otherwise use CsoundUnity version 3.2.1

**Comment by giovannibedetti** [comment]
Fix available in this branch: fix-linkbutton
use this package git url to test it: https://github.com/rorywalsh/CsoundUnity.git#fix-linkbutton

**Comment by nathanjams** [comment]
Hello, 

Just upgraded my project to 2021.1.28 and can confirm that the existing package worked with this version of Unity. 
Thanks for getting back to me so quickly. 

Haven't used CSound since I was in university a long time ago. Extremely excited to start a Unity project with it! Thank you so much for making this possible ;)

**Comment by giovannibedetti** [comment]
version 3.3.1 fixed this issue:
https://github.com/rorywalsh/CsoundUnity/releases/tag/v3.3.1
you can now use again the master branch on Unity versions older than 2021.1.

Feel free to post your progress or questions on https://forum.cabbageaudio.com/ or https://forum.csound.com/, I'm very curious to see what people can create with this package!

closing the issue!

**Comment by giovannibedetti** [comment]
@all-contributors add @nathanjams for bug
