### ISSUE TITLE
Unity Crash

### ISSUE THREAD

**Issue by MarcoTheCat** [rorywalsh/CsoundUnity#4]
Hello, I am very excited by the possibility of using Csound in my Unity3D projects.  Recently I have run into an issue where Unity3D crashes when I issue the first event call to Csound.  I have been successful at putting Csound into a couple of other projects but in this case drastic things happen whenever I try to use Csound.  The event call issued is:
		csoundUnity.sendScoreEvent ("i 2 0 3600");

This is after a couple of setChannel calls:
		csoundUnity.setChannel("kcents", pitchInCents);
		csoundUnity.setChannel ("amplitude", 1.0f * volumeFactor);

I removed the sendScoreEvent call and Unity still crashed.  I have removed the CsoundUnity
Most of the time there is no crash log, although once I did receive it and noticed that a pointer was being freed that was uninitialized.  
I am using Unity 5.6.1f1 on a Mac running 10.12.6
I am including the csound file.  Please let me know if there is anything I can do further to help get at the problem.
Thank you!
#

**Comment by rorywalsh** [comment]
Your score finishes as soon as it starts. You should add 
`f0 z`
This will keep Csound running and waiting for events to arrive. Btw, sorry for the delay in getting back to you. For a quicker response you can try the [Csound for Games](http://forum.cabbageaudio.com/c/csound-for-games) forum on the CabbageAudio site

p.s. if this works, can you close the issue ;)

**Comment by MarcoTheCat** [comment]
Thank you very much for your support.I made the change but it didn't help, I still got a Unity hang.The main difference I made in creating this project was that I left out some of the assets from the CsoundUnityOSX package (mostly assets I didn't need, like the scenes and their related assets).  Maybe there was something I should have included that I didn't.  Is there a definitive list of what is necessary to import to a new project?  I assumed it was basically the cSoundLib64 framework - do I need anything else?  CsoundUnityScripts?  Also, how do I know I have the latest package?
Anyway, I rebuild the project from scratch and it works, yay!
I will use the Csound for Games forum in the future, and thank you for your work in improving sound possibilities in Unity exponentially, and for Cabbage!
Best,Tom
 

    On Saturday, August 5, 2017 6:52 AM, Rory Walsh <notifications@github.com> wrote:
 

 Your score finishes as soon as it starts. You should add
f0 z
This will keep Csound running and waiting for events to arrive. Btw, sorry for the delay in getting back to you. For a quicker response you can try the Csound for Games forum on the CabbageAudio site—

**Comment by rorywalsh** [comment]
After installing the package you can remove/replace any files from the CsoundScripts folder but you'll need to keep everything else, most definitely the CsoundUnityScripts! Glad it's working. Hope to see you over on the forum some time ;)
