### ISSUE TITLE
Drag&Drop stops working in Unity Editor on Windows

### ISSUE THREAD

**Issue by giovannibedetti** [rorywalsh/CsoundUnity#42]
After playing a scene with a CsoundUnity instance, drag&drop in the Unity Editor stops working.
Restarting the Editor fixes it. 
Not reproduced on MacOS (any version).
Reproduced with all Unity versions on Windows with Csound v6.18 and v6.17

**Comment by giovannibedetti** [comment]
It is probably caused by FLTK opcodes, that are present in the Windows version of Csound 6.17.
EDIT:
The same behaviour is happening with Csound 6.18.

To (possibly) fix the drag&drop issue, rebuild csound64.dll without the FLTK opcodes.

EDIT:
Removing Csound and Csound plugins from the PATH doesn't help

**Comment by rorywalsh** [comment]
Fixed

**Comment by ceberman** [comment]
Hi, Giovanni, I just noticed the comment about FLTK opcodes, and just checking (and hoping that) the other sound font opcodes will continue to be supported (sfload, sfinstr) in future versions.

PS: Thanks again for all the ongoing work on this

**Comment by giovannibedetti** [comment]
Hi Charles, the issue was related with how we were handling the destruction of Csound. It wasn't related with FLTK opcodes. Just changing the order of operations fixed the issue.
So no need to remove any opcode and rebuild Csound. The csound64.dll will be the one that comes with each Csound release.
The fix will come in a patch release (3.4.1) soon

**Comment by giovannibedetti** [comment]
@all-contributors add @giovannibedetti for bug
