### ISSUE TITLE
CsoundUnity awake() function overwrites Path variable

### ISSUE THREAD

**Issue by cmccauley** [rorywalsh/CsoundUnity#5]
This breaks the Unity VRTK Plugin.
System.Environment.SetEnvironmentVariable("Path", Application.streamingAssetsPath);

We should Append the assets path to the current System.Environment.GetEnvironmentVariable("Path")

**Comment by rorywalsh** [comment]
I've no access to a PC right now, but if you make a PR I can merge from my phone ;)

**Comment by rorywalsh** [comment]
I finally got around to do this. Cheers. I'll close this out now.

**Comment by cmccauley** [comment]
Totally forgot about this. Thanks !

**Comment by rorywalsh** [comment]
So had I until another user remarked on it! Glad it's sorted now.
