### ISSUE TITLE
ios namespace error

### ISSUE THREAD

**Issue by composingcap** [rorywalsh/CsoundUnity#65]
On windows, I get this error with csound unity installed:

Library\PackageCache\com.csound.csoundunity@876b530e01\Editor\CsoundUnityPostProcessBuild.cs(5,19): error CS0234: The type or namespace name 'iOS' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)

I am guessing it needs a macro to check if Unity has IOS build support installed as it does not seem this is included in Unity's windows build support.

**Comment by composingcap** [comment]
#if UNITY_IOS should work I think

**Comment by giovannibedetti** [comment]
hotfix pushed to Master branch.
