### ISSUE TITLE
Can't get output from CsoundUnity as .wav with -o 

### ISSUE THREAD

**Issue by koenfrontatie** [rorywalsh/CsoundUnity#70]
Hey, I've been trying to get a wav file as an output from my CsoundUnity class. I've been using this example:

<CsoundSynthesizer>
<CsOptions>
-o output.wav
</CsOptions>
<CsInstruments>
;Example by Alex Hofmann
instr 1
aSin      poscil    0dbfs/4, 440
          out       aSin
endin
</CsInstruments>
<CsScore>
i 1 0 1
</CsScore>
</CsoundSynthesizer>

Sadly, an audio file never appears in any environment folder.
Could you help me?

**Comment by koenfrontatie** [comment]
https://forum.cabbageaudio.com/t/unable-to-create-output-file-solved/985

i've come across this back and forth.  i think this is leading me in the right direction, i suppose im not knowledgeable enough yet.
is there no way to run non real time stuff from csoundunity without having to do command line stuff or somethign? i'd like to render certain effects on android ideally

**Comment by giovannibedetti** [comment]
The suggested approach using fout should work. Be sure to set the SFDIR for Android in the CsoundUnity Environment settings. Point it to the PersistentDataPath folder and you should find a file there after running the csd. 
Report here if you have problems

**Comment by giovannibedetti** [comment]
just tested the basic approach using **fout**, it works fine on macOs. 
**It's important to set the SFDIR**, for example like this:
![image](https://github.com/rorywalsh/CsoundUnity/assets/1912983/37417c9d-0ab8-49cf-b290-ae258d3eb145)
attached the csd used to test this. Press play in editor, and wait until you see "_Score finished in csoundPerformKsmps() with 2._" being logged. You should then find a 3 seconds aif file in the **persistent data path folder**.
[testRec.csd.zip](https://github.com/rorywalsh/CsoundUnity/files/15296718/testRec.csd.zip)
